version: "3"

services:
  project-x-node-app:
    build: 
      context: node
    container_name: project-x-node-app
    networks: 
      - project-x-network
    volumes:
      - ./node:/usr/src/project-x-node-app
    tty: true
    ports:
      - "1337:3000"


  project-x-db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: project-x-db
    restart: always
    tty: true
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=project-x-db
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - project-x-network

networks:
  project-x-network:
    driver: bridge
