### Dockerfile é o arquivo principal para construção da imagem do container 

## from é a imagem base para a construção da imagem do container

FROM nginx:latest


## RUN é o comando que executa dentro do container
RUN apt-get update && apt-get install nano -y


## para gerar essa imagem docker basta executar o comando abaixo
## docker build -t nome_da_imagem:tag .