FROM ubuntu:latest

## ENTRYPOINT é o comando que executa dentro do container
# se nao houver entrypoint o cmd é executado como comando  
ENTRYPOINT ["echo", "Hello,"]

## CMD é o argumento do ENTRYPOINT

CMD ["world"]